/*
 * This file is part of HeavySpleef.
 * Copyright (c) 2014-2016 Matthias Werning
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package de.xaniox.heavyspleef.core.uuid;

import java.util.UUID;

public class OriginalGameProfile extends GameProfile {

	private String originalName;
	
	public OriginalGameProfile(UUID uniqueIdentifier, String currentName, String originalName) {
		super(uniqueIdentifier, currentName);
		
		this.originalName = originalName;
	}
	
	public String getOriginalName() {
		return originalName;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((originalName == null) ? 0 : originalName.hashCode());
		return result;
	}

	/* Previously generated by lombok */
	@Override
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof OriginalGameProfile)) return false;
		final OriginalGameProfile other = (OriginalGameProfile)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$originalName = this.getOriginalName();
		final java.lang.Object other$originalName = other.getOriginalName();
		if (this$originalName == null ? other$originalName != null : !this$originalName.equals(other$originalName)) return false;
		return true;
	}
	
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof OriginalGameProfile;
	}
	
}